# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
# set to match https://github.com/scikit-learn/scikit-learn/blob/main/.pre-commit-config.yaml
exclude: '^(\.tox|ci/templates|\.bumpversion\.cfg)(/|$)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.272
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: ["--fix", "--show-source"]
  - repo: https://github.com/psf/black
    # including black in addition to ruff to match the scikit-learn pre-commit config
    rev: 23.3.0
    hooks:
    - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
     -  id: mypy
        files: sklearn/
        additional_dependencies: [pytest==6.2.4]
  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.15.0
    hooks:
    # TODO: add the double-quote-cython-strings hook when it's usability has improved:
    # possibility to pass a directory and use it as a check instead of auto-formatter.
    -   id: cython-lint
